Assorted consistency tweaks

diff --git a/log2ram b/log2ram
--- a/log2ram
+++ b/log2ram
@@ -1,31 +1,34 @@
 #!/usr/bin/env bash
 
+# shellcheck disable=SC1091
 . /etc/log2ram.conf
 
-if [ -z "$PATH_DISK" ]; then
+if [[ -z "${PATH_DISK}" ]]; then
     PATH_DISK='/var/log'
 fi
 
 LOG_NAME='log2ram.log'
 NO_RSYNC=${USE_RSYNC#true}
-NOTIFICATION_COMMAND=${NOTIFICATION_COMMAND:=mail -s "Log2Ram Error on $HOSTNAME" root}
+NOTIFICATION_COMMAND=${NOTIFICATION_COMMAND:=mail -s "Log2Ram Error on ${HOSTNAME}" root}
 NOTIFICATION=${NOTIFICATION:=true}
 
 ## @fn is_safe()
 ## @brief Check if hdd log exists
 is_safe() {
-    [ -d "$HDD_LOG" ] || echo "ERROR: $HDD_LOG/ doesn't exist! Can't sync."
-    [ -d "$HDD_LOG" ] || exit 1
+    if [[ ! -d "${HDD_LOG}" ]]; then
+        echo "ERROR: ${HDD_LOG}/ doesn't exist! Can't sync."
+        exit 1
+    fi
 }
 
 ## @fn journald_logrotate()
 ## @brief Logrotate the journal if the current RAM_LOG path is part of the journald directory
 journald_logrotate() {
-    if ! [ -x "$(command -v journalctl)" ] || ! [ "$JOURNALD_AWARE" = true ]; then
+    if ! [[ -x "$(command -v journalctl)" ]] || ! [[ "${JOURNALD_AWARE}" == true ]]; then
         return 1
     fi
 
-    if journalctl --header | grep "File path" | grep "$RAM_LOG" >/dev/null 2>&1; then
+    if journalctl --header | grep "File path" | grep "${RAM_LOG}" >/dev/null 2>&1; then
         journalctl --rotate
         return 0
     else
@@ -38,18 +41,18 @@ journald_logrotate() {
 sync_to_disk() {
     is_safe
 
-    optional_params=()
+    local optional_params=()
 
     if journald_logrotate; then
         optional_params+=("--include=journal/*/*@*.journal")
         optional_params+=("--exclude=journal/*/*")
     fi
 
-    if [ -z "${NO_RSYNC}" ] && [ -x "$(command -v rsync)" ]; then
-        rsync -aAXv --sparse --inplace --no-whole-file --delete-after "${optional_params[@]}" "$RAM_LOG"/ "$HDD_LOG"/ 2>&1 |
-            tee -a "$LOG2RAM_LOG"
+    if [[ -z "${NO_RSYNC}" ]] && [[ -x "$(command -v rsync)" ]]; then
+        rsync -aAXv --sparse --inplace --no-whole-file --delete-after "${optional_params[@]}" "${RAM_LOG}"/ "${HDD_LOG}"/ 2>&1 |
+            tee -a "${LOG2RAM_LOG}"
     else
-        cp -rfup --sparse=always "$RAM_LOG"/ -T "$HDD_LOG"/ 2>&1 | tee -a "$LOG2RAM_LOG"
+        cp -rfup --sparse=always "${RAM_LOG}"/ -T "${HDD_LOG}"/ 2>&1 | tee -a "${LOG2RAM_LOG}"
     fi
 }
 
@@ -58,88 +61,94 @@ sync_to_disk() {
 sync_from_disk() {
     is_safe
 
-    TP_SIZE=$SIZE
-    if [ "$ZL2R" = true ]; then
-        TP_SIZE=$LOG_DISK_SIZE
+    local TP_SIZE="${SIZE}"
+    if [[ "${ZL2R}" == true ]]; then
+        TP_SIZE="${LOG_DISK_SIZE}"
     fi
 
-    if [ -n "$(du -sh -t "$TP_SIZE" "$HDD_LOG"/ | cut -f1)" ]; then
-        echo "ERROR: RAM disk for \"$HDD_LOG/\" too small. Can't sync."
-        echo -e "File(s) causing issues\n: $(du -sh -t "$TP_SIZE" "$HDD_LOG"/*)"
-        umount -l "$RAM_LOG"/
-        umount -l "$HDD_LOG"/
-        if [ "$NOTIFICATION" = true ]; then
-            echo "LOG2RAM : No place on RAM for \"$HDD_LOG/\" anymore, fallback on the disk" | $NOTIFICATION_COMMAND
+    if [[ -n "$(du -sh -t "${TP_SIZE}" "${HDD_LOG}"/ | cut -f1)" ]]; then
+        echo "ERROR: RAM disk for \"${HDD_LOG}/\" too small. Can't sync."
+        echo -e "File(s) causing issues\n: $(du -sh -t "${TP_SIZE}" "${HDD_LOG}"/*)"
+        umount -l "${RAM_LOG}"/
+        umount -l "${HDD_LOG}"/
+        if [[ "${NOTIFICATION}" == true ]]; then
+            echo "LOG2RAM: No place on RAM for \"${HDD_LOG}/\" anymore, fallback on the disk" | ${NOTIFICATION_COMMAND}
         fi
         exit 1
     fi
 
-    if [ -z "${NO_RSYNC}" ] && [ -x "$(command -v rsync)" ]; then
-        rsync -aAXv --sparse --inplace --no-whole-file --delete-after "$HDD_LOG"/ "$RAM_LOG"/ 2>&1 | tee -a "$LOG2RAM_LOG"
+    if [[ -z "${NO_RSYNC}" ]] && [[ -x "$(command -v rsync)" ]]; then
+        rsync -aAXv --sparse --inplace --no-whole-file --delete-after "${HDD_LOG}"/ "${RAM_LOG}"/ 2>&1 | tee -a "${LOG2RAM_LOG}"
     else
-        cp -rfup --sparse=always "$HDD_LOG"/ -T "$RAM_LOG"/ 2>&1 | tee -a "$LOG2RAM_LOG"
+        cp -rfup --sparse=always "${HDD_LOG}"/ -T "${RAM_LOG}"/ 2>&1 | tee -a "${LOG2RAM_LOG}"
     fi
-
 }
 
 ## @fn wait_for()
 ## @brief Wait for directory and create test file to make sure the directory exists
 ## @param param1 path to the directory
 wait_for() {
-    WAIT_PATH="$1"
-    while ! findmnt "$WAIT_PATH" >/dev/null; do
+    local WAIT_PATH="$1"
+    while ! findmnt "${WAIT_PATH}" >/dev/null; do
         sleep 0.1
     done
 
-    while [ ! -f "$WAIT_PATH/log2ram.test" ]; do
-        touch "$WAIT_PATH/log2ram.test"
+    while [[ ! -f "${WAIT_PATH}/log2ram.test" ]]; do
+        touch "${WAIT_PATH}/log2ram.test"
         sleep 0.1
     done
-    rm "$WAIT_PATH/log2ram.test"
+    rm "${WAIT_PATH}/log2ram.test"
 }
 
 ## @fn create_zram_log_drive()
 ## @brief Create zram log device
 create_zram_log_drive() {
     # Check Zram Class created
-    if [ ! -d "/sys/class/zram-control" ]; then
+    if [[ ! -d "/sys/class/zram-control" ]]; then
         modprobe zram
         RAM_DEV='0'
     else
-        RAM_DEV=$(cat /sys/class/zram-control/hot_add)
+        RAM_DEV=$(</sys/class/zram-control/hot_add)
     fi
-    echo "$COMP_ALG" >"/sys/block/zram${RAM_DEV}/comp_algorithm"
-    echo "$LOG_DISK_SIZE" >"/sys/block/zram${RAM_DEV}/disksize"
-    echo "$SIZE" >"/sys/block/zram${RAM_DEV}/mem_limit"
+    echo "${COMP_ALG}" >"/sys/block/zram${RAM_DEV}/comp_algorithm"
+    echo "${LOG_DISK_SIZE}" >"/sys/block/zram${RAM_DEV}/disksize"
+    echo "${SIZE}" >"/sys/block/zram${RAM_DEV}/mem_limit"
     mke2fs -t ext4 "/dev/zram${RAM_DEV}"
+}
+
+## @fn parse_paths()
+## @brief Extract RAM and HDD paths from a given log path
+parse_paths() {
+    local i="$1"
+    PATH_FIRST_PART="${i%/*}"
+    PATH_LAST_PART="${i##/*/}"
+    RAM_LOG="${i}"
+    HDD_LOG="${PATH_FIRST_PART}/hdd.${PATH_LAST_PART}"
+    LOG2RAM_LOG="${RAM_LOG}/${LOG_NAME}"
 }
 
 case "$1" in
 start)
     IFS=';'
-    for i in $PATH_DISK; do
+    for i in ${PATH_DISK}; do
         # Skip the path if the folder doesn't exist
-        [ ! -d "$i" ] && continue
+        [[ ! -d "${i}" ]] && continue
 
-        PATH_FIRST_PART="${i%/*}"
-        PATH_LAST_PART="${i##/*/}"
-        RAM_LOG="$i"
-        HDD_LOG="${PATH_FIRST_PART}/hdd.${PATH_LAST_PART}"
-        LOG2RAM_LOG="${RAM_LOG}/${LOG_NAME}"
+        parse_paths "${i}"
 
-        [ -d "$HDD_LOG" ] || mkdir "$HDD_LOG"
+        [[ -d "${HDD_LOG}" ]] || mkdir "${HDD_LOG}"
 
-        mount --bind "$RAM_LOG"/ "$HDD_LOG"/
-        mount --make-private "$HDD_LOG"/
-        wait_for "$HDD_LOG"
+        mount --bind "${RAM_LOG}"/ "${HDD_LOG}"/
+        mount --make-private "${HDD_LOG}"/
+        wait_for "${HDD_LOG}"
 
-        if [ "$ZL2R" = true ]; then
+        if [[ "${ZL2R}" == true ]]; then
             create_zram_log_drive
-            mount -t ext4 -o nosuid,noexec,noatime,nodev,user=log2ram "/dev/zram${RAM_DEV}" "$RAM_LOG"/
+            mount -t ext4 -o nosuid,noexec,noatime,nodev,user=log2ram "/dev/zram${RAM_DEV}" "${RAM_LOG}"/
         else
-            mount -t tmpfs -o "nosuid,noexec,noatime,nodev,mode=0755,size=${SIZE}" log2ram "$RAM_LOG"/
+            mount -t tmpfs -o "nosuid,noexec,noatime,nodev,mode=0755,size=${SIZE}" log2ram "${RAM_LOG}"/
         fi
-        wait_for "$RAM_LOG"
+        wait_for "${RAM_LOG}"
         sync_from_disk
     done
     exit 0
@@ -147,18 +156,13 @@ start)
 
 stop)
     IFS=';'
-    for i in $PATH_DISK; do
-        PATH_FIRST_PART="${i%/*}"
-        PATH_LAST_PART="${i##/*/}"
-        RAM_LOG="$i"
-        HDD_LOG="${PATH_FIRST_PART}/hdd.${PATH_LAST_PART}"
-        LOG2RAM_LOG="${RAM_LOG}/${LOG_NAME}"
-
+    for i in ${PATH_DISK}; do
+        parse_paths "${i}"
         sync_to_disk
         #ZRAM_LOG=$(awk '$2 == "/var/log" {print $1}' /proc/mounts)
         #ZRAM_LOG=$(echo ${ZRAM_LOG} | grep -o -E '[0-9]+')
-        umount -l "$RAM_LOG"/
-        umount -l "$HDD_LOG"/
+        umount -l "${RAM_LOG}"/
+        umount -l "${HDD_LOG}"/
         # Unsure as even with Root permision denied
         #echo ${ZRAM_LOG} > /sys/class/zram-control/hot_remove
     done
@@ -167,13 +171,8 @@ stop)
 
 write)
     IFS=';'
-    for i in $PATH_DISK; do
-        PATH_FIRST_PART="${i%/*}"
-        PATH_LAST_PART="${i##/*/}"
-        RAM_LOG="$i"
-        HDD_LOG="${PATH_FIRST_PART}/hdd.${PATH_LAST_PART}"
-        LOG2RAM_LOG="${RAM_LOG}/${LOG_NAME}"
-
+    for i in ${PATH_DISK}; do
+        parse_paths "${i}"
         sync_to_disk
     done
     exit 0
