Sync the ramlog back to disk, hourly.
- Since the cron job could be called before the user reboots after
  install (or if log2ram is disabled), we check that the hdd log
  location exists before syncing.

- Copy the log2ram.hourly sync script to cron's hourly directory on
  install.

diff --git a/log2ram b/log2ram
--- a/log2ram
+++ b/log2ram
@@ -7,6 +7,9 @@ SIZE=40M
 USE_RSYNC=false
 
 sync () {
+    [ -d $HDD_LOG ] || echo "ERROR: $HDD_LOG doesn't exist!  Can't sync."
+    [ -d $HDD_LOG ] || exit 1
+
     if [ "$USE_RSYNC" = true ]; then
         rsync -aXWv --delete --links $HDD_LOG $RAM_LOG 2>&1 | tee -a $LOG2RAM_LOG
     else
