Fixed consistent naming of /var/hdd.log

diff --git a/log2ram b/log2ram
--- a/log2ram
+++ b/log2ram
@@ -5,11 +5,12 @@
 HDD_LOG=/var/hdd.log
 RAM_LOG=/var/log
 
-LOG2RAM_LOG="${HDD_LOG}/log2ram.log"
+LOG_NAME="log2ram.log"
+LOG2RAM_LOG="${HDD_LOG}/${LOG_NAME}"
 LOG_OUTPUT="tee -a $LOG2RAM_LOG"
 
 isSafe () {
-    [ -d $HDD_LOG/ ] || echo "ERROR: $HDD_LOG/ doesn't exist!  Can't sync."
+    [ -d $HDD_LOG/ ] || echo "ERROR: $HDD_LOG/ doesn't exist! Can't sync."
     [ -d $HDD_LOG/ ] || exit 1
 }
 
@@ -17,7 +18,7 @@ syncToDisk () {
     isSafe
 
     if [ "$USE_RSYNC" = true ]; then
-        rsync -aXWv --delete --exclude log2ram.log --links $RAM_LOG/ $HDD_LOG/ 2>&1 | $LOG_OUTPUT
+        rsync -aXWv --delete --exclude $LOG_NAME --links $RAM_LOG/ $HDD_LOG/ 2>&1 | $LOG_OUTPUT
     else
         cp -rfup $RAM_LOG/ -T $HDD_LOG/ 2>&1 | $LOG_OUTPUT
     fi
@@ -30,14 +31,14 @@ syncFromDisk () {
         echo "ERROR: RAM disk too small. Can't sync."
         umount -l $RAM_LOG/
         umount -l $HDD_LOG/
-		if [ "$MAIL" = true ]; then
-			echo "LOG2RAM : No place on RAM anymore, fallback on the disk" | mail -s 'Log2Ram Error' root;
-		fi
+        if [ "$MAIL" = true ]; then
+            echo "LOG2RAM : No place on RAM anymore, fallback on the disk" | mail -s 'Log2Ram Error' root;
+        fi
         exit 1
     fi
 
     if [ "$USE_RSYNC" = true ]; then
-        rsync -aXWv --delete --exclude log2ram.log --links $HDD_LOG/ $RAM_LOG/ 2>&1 | $LOG_OUTPUT
+        rsync -aXWv --delete --exclude $LOG_NAME --links $HDD_LOG/ $RAM_LOG/ 2>&1 | $LOG_OUTPUT
     else
         cp -rfup $HDD_LOG/ -T $RAM_LOG/ 2>&1 | $LOG_OUTPUT
     fi
@@ -45,17 +46,17 @@ syncFromDisk () {
 
 wait_for () {
     while ! grep -qs $1 /proc/mounts; do
-        sleep 0.1 
-    done   
+        sleep 0.1
+    done
 }
 
 case "$1" in
   start)
       [ -d $HDD_LOG/ ] || mkdir $HDD_LOG/
-      rm -f $LOG2RAM_LOG
       mount --bind $RAM_LOG/ $HDD_LOG/
       mount --make-private $HDD_LOG/
       wait_for $HDD_LOG
+      rm -f $LOG2RAM_LOG
       mount -t tmpfs -o nosuid,noexec,nodev,mode=0755,size=$SIZE log2ram $RAM_LOG/
       wait_for $RAM_LOG
       syncFromDisk
@@ -70,7 +71,7 @@ case "$1" in
   write)
       syncToDisk
       ;;
-	  
+
   *)
       echo "Usage: log2ram {start|stop|write}" >&2
       exit 1
